title: Laboratoire ERPI
short_title: erpi
description: Site web pour le Laboratoire ERPI 
baseurl:
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
  projects:
    output: true
    permalink: "/projects/:path/"
  publications:
    output: true
    permalink: "/publications/:path/" 
# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"

plugins:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
